"""FastAPI backend for the health risk app.

Run from the project folder:
    uvicorn app.backend.main:app --reload

Endpoints:
    GET  /api/health    -> confirms the server is up and how many models loaded
    POST /api/predict   -> takes a person's answers (PersonInput), returns risk for every condition
    GET  /docs          -> interactive API docs generated by FastAPI (try requests in the browser)

If the React app has been built (app/frontend/dist), it is also served at http://localhost:8000/.
"""
from contextlib import asynccontextmanager
from pathlib import Path

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles

from .risk_engine import PersonInput, RiskEngine

engine: RiskEngine | None = None


@asynccontextmanager
async def lifespan(app: FastAPI):
    # Load all 20 models once at startup so each request is fast
    global engine
    engine = RiskEngine()
    yield


app = FastAPI(title="Health Risk API", lifespan=lifespan)

# Allow the React dev server (Vite, port 5173) to call this API
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:5173", "http://127.0.0.1:5173"],
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.get("/api/health")
def health():
    return {"status": "ok", "models_loaded": len(engine.models) if engine else 0}


@app.post("/api/predict")
def predict(person: PersonInput):
    try:
        return engine.predict(person)
    except ValueError as e:
        raise HTTPException(status_code=422, detail=str(e))


# Serve the built frontend (after `npm run build`) so the whole app runs from one server
DIST = Path(__file__).resolve().parents[1] / "frontend" / "dist"
if DIST.exists():
    app.mount("/", StaticFiles(directory=DIST, html=True), name="frontend")
